---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ11N16" #see SAP Continuous Integration and Delivery service for more build tool version options
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "Sistemas_Globales_S.A_Globant"
    cfSpace: "DEV"
    cfAppName: "Apptest"
    cfCredentialsId: "deploy-to-cf"
    deployType: "standard"
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "Sistemas_Globales_S.A_Globant"
    cfSpace: "DEV"
    cfAppName: "Apptest"
    cfCredentialsId: "deploy-to-cf"
    deployType: "standard"
    tmsUpload: true #Estaba en False fue el segundo cambio para que se cargara para el tms
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "QAS" #Estaba qa pero lo cambiamos por nuestro nombre
    credentialsId: "tms-sk" #El nombre de las credenciales la puedes elegir pero debe de ser el mismo nombre que eliges para el CICD en el apartado de credenciales
